//! Code generation from sproto schema text to Rust struct source code.
//!
//! This module converts sproto schema definitions into Rust structs
//! with appropriate derive macros and attributes. Supports generating
//! code for the Derive API, Serde API, or both.
//!
//! # Example
//!
//! ```
//! use sproto::codegen::{generate, CodegenMode};
//!
//! let schema = r#"
//! .PhoneNumber {
//!     number 0 : string
//!     type 1 : integer
//! }
//! .Person {
//!     name 0 : string
//!     age 1 : integer
//!     phone 2 : *PhoneNumber
//! }
//! "#;
//!
//! let code = generate(&[schema], CodegenMode::Derive).unwrap();
//! assert!(code.contains("pub struct PhoneNumber"));
//! assert!(code.contains("pub struct Person"));
//! ```

use std::fmt::Write;

use crate::error::ParseError;
use crate::parser;
use crate::types::{FieldType, Sproto};

/// Code generation mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenMode {
    /// Generate structs with `#[derive(SprotoEncode, SprotoDecode)]`.
    Derive,
    /// Generate structs with `#[derive(Serialize, Deserialize)]`.
    Serde,
    /// Generate structs with both derive sets.
    Both,
}

/// Rust keywords that require `r#` prefix when used as identifiers.
const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn",
];

/// Generate Rust source code from one or more sproto schema strings.
///
/// Multiple schemas are concatenated before parsing, so types defined
/// in different files can reference each other freely.
///
/// Returns the generated Rust source code as a `String`.
pub fn generate(schema_texts: &[&str], mode: CodegenMode) -> Result<String, ParseError> {
    let combined = schema_texts.join("\n");
    let sproto = parser::parse(&combined)?;
    let mut out = String::new();

    writeln!(out, "// Auto-generated by sproto-codegen. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();

    write_imports(&mut out, mode, &sproto);

    if needs_opt_bytes(mode, &sproto) {
        write_opt_bytes_module(&mut out);
    }

    for st in &sproto.types_list {
        write_struct(&mut out, st, &sproto, mode);
    }

    // Remove trailing blank line
    if out.ends_with("\n\n") {
        out.pop();
    }

    Ok(out)
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn escape_keyword(name: &str) -> String {
    if RUST_KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// Convert a sproto type name (e.g. `"Person.PhoneNumber"`) to a valid Rust
/// struct identifier (e.g. `"Person_PhoneNumber"`).
fn type_name_to_rust(name: &str) -> String {
    name.replace('.', "_")
}

fn has_binary_fields(sproto: &Sproto) -> bool {
    sproto.types_list.iter().any(|st| {
        st.fields
            .iter()
            .any(|f| matches!(f.field_type, FieldType::Binary))
    })
}

fn needs_opt_bytes(mode: CodegenMode, sproto: &Sproto) -> bool {
    matches!(mode, CodegenMode::Serde | CodegenMode::Both) && has_binary_fields(sproto)
}

// ---- imports --------------------------------------------------------------

fn write_imports(out: &mut String, mode: CodegenMode, sproto: &Sproto) {
    match mode {
        CodegenMode::Derive => {
            writeln!(out, "use sproto::{{SprotoEncode, SprotoDecode}};").unwrap();
        }
        CodegenMode::Serde => {
            writeln!(out, "use serde::{{Serialize, Deserialize}};").unwrap();
            if has_binary_fields(sproto) {
                writeln!(out, "use serde_bytes;").unwrap();
            }
        }
        CodegenMode::Both => {
            writeln!(out, "use serde::{{Serialize, Deserialize}};").unwrap();
            writeln!(out, "use sproto::{{SprotoEncode, SprotoDecode}};").unwrap();
            if has_binary_fields(sproto) {
                writeln!(out, "use serde_bytes;").unwrap();
            }
        }
    }
    writeln!(out).unwrap();
}

// ---- opt_bytes helper module ----------------------------------------------

fn write_opt_bytes_module(out: &mut String) {
    writeln!(out, "mod opt_bytes {{").unwrap();
    writeln!(out, "    use serde::{{Deserializer, Serializer}};").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    pub fn serialize<S: Serializer>(val: &Option<Vec<u8>>, s: S) -> Result<S::Ok, S::Error> {{"
    )
    .unwrap();
    writeln!(out, "        match val {{").unwrap();
    writeln!(out, "            Some(b) => serde_bytes::serialize(b, s),").unwrap();
    writeln!(out, "            None => s.serialize_none(),").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<Vec<u8>>, D::Error> {{"
    )
    .unwrap();
    writeln!(out, "        Ok(Some(serde_bytes::deserialize(d)?))").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// ---- struct generation ----------------------------------------------------

fn write_struct(
    out: &mut String,
    st: &crate::types::SprotoType,
    sproto: &Sproto,
    mode: CodegenMode,
) {
    let struct_name = type_name_to_rust(&st.name);

    // Derive line
    match mode {
        CodegenMode::Derive => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Default, SprotoEncode, SprotoDecode)]"
            )
            .unwrap();
        }
        CodegenMode::Serde => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]"
            )
            .unwrap();
        }
        CodegenMode::Both => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize, SprotoEncode, SprotoDecode)]"
            )
            .unwrap();
        }
    }

    writeln!(out, "pub struct {struct_name} {{").unwrap();

    for field in &st.fields {
        write_field(out, field, sproto, mode);
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn write_field(out: &mut String, field: &crate::types::Field, sproto: &Sproto, mode: CodegenMode) {
    let field_name = escape_keyword(&field.name);
    let is_binary = matches!(field.field_type, FieldType::Binary);

    // Attributes
    match mode {
        CodegenMode::Derive => {
            writeln!(out, "    #[sproto(tag = {})]", field.tag).unwrap();
        }
        CodegenMode::Serde => {
            write_serde_attr(out, is_binary, field.is_array);
        }
        CodegenMode::Both => {
            writeln!(out, "    #[sproto(tag = {})]", field.tag).unwrap();
            write_serde_attr(out, is_binary, field.is_array);
        }
    }

    // Type
    let rust_type = field_rust_type(field, sproto);
    writeln!(out, "    pub {field_name}: {rust_type},").unwrap();
}

fn write_serde_attr(out: &mut String, is_binary: bool, is_array: bool) {
    if is_binary && !is_array {
        writeln!(
            out,
            "    #[serde(default, skip_serializing_if = \"Option::is_none\", with = \"opt_bytes\")]"
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "    #[serde(default, skip_serializing_if = \"Option::is_none\")]"
        )
        .unwrap();
    }
}

fn field_rust_type(field: &crate::types::Field, sproto: &Sproto) -> String {
    let base = match &field.field_type {
        FieldType::Integer => "i64".to_string(),
        FieldType::Boolean => "bool".to_string(),
        FieldType::Double => "f64".to_string(),
        FieldType::String => "String".to_string(),
        FieldType::Binary => "Vec<u8>".to_string(),
        FieldType::Struct(idx) => type_name_to_rust(&sproto.types_list[*idx].name),
    };

    if field.is_array {
        format!("Option<Vec<{base}>>")
    } else {
        format!("Option<{base}>")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SCHEMA: &str = include_str!("../tests/testdata/schema.sproto");

    #[test]
    fn test_escape_keyword() {
        assert_eq!(escape_keyword("type"), "r#type");
        assert_eq!(escape_keyword("name"), "name");
        assert_eq!(escape_keyword("fn"), "r#fn");
    }

    #[test]
    fn test_type_name_to_rust() {
        assert_eq!(type_name_to_rust("Person"), "Person");
        assert_eq!(
            type_name_to_rust("Person.PhoneNumber"),
            "Person_PhoneNumber"
        );
    }

    #[test]
    fn test_generate_derive_mode() {
        let code = generate(&[SCHEMA], CodegenMode::Derive).unwrap();
        let expected = "\
// Auto-generated by sproto-codegen. DO NOT EDIT.

use sproto::{SprotoEncode, SprotoDecode};

#[derive(Debug, Clone, PartialEq, Default, SprotoEncode, SprotoDecode)]
pub struct Person {
    #[sproto(tag = 0)]
    pub name: Option<String>,
    #[sproto(tag = 1)]
    pub age: Option<i64>,
    #[sproto(tag = 2)]
    pub active: Option<bool>,
    #[sproto(tag = 3)]
    pub score: Option<f64>,
    #[sproto(tag = 4)]
    pub photo: Option<Vec<u8>>,
    #[sproto(tag = 5)]
    pub fpn: Option<i64>,
    #[sproto(tag = 6)]
    pub id: Option<i64>,
    #[sproto(tag = 7)]
    pub phone: Option<PhoneNumber>,
    #[sproto(tag = 8)]
    pub phones: Option<Vec<PhoneNumber>>,
    #[sproto(tag = 9)]
    pub children: Option<Vec<Person>>,
    #[sproto(tag = 10)]
    pub tags: Option<Vec<String>>,
    #[sproto(tag = 11)]
    pub numbers: Option<Vec<i64>>,
    #[sproto(tag = 12)]
    pub flags: Option<Vec<bool>>,
    #[sproto(tag = 13)]
    pub values: Option<Vec<f64>>,
}

#[derive(Debug, Clone, PartialEq, Default, SprotoEncode, SprotoDecode)]
pub struct PhoneNumber {
    #[sproto(tag = 0)]
    pub number: Option<String>,
    #[sproto(tag = 1)]
    pub r#type: Option<i64>,
}
";
        assert_eq!(code, expected);
    }

    #[test]
    fn test_generate_serde_mode() {
        let code = generate(&[SCHEMA], CodegenMode::Serde).unwrap();
        let expected = "\
// Auto-generated by sproto-codegen. DO NOT EDIT.

use serde::{Serialize, Deserialize};
use serde_bytes;

mod opt_bytes {
    use serde::{Deserializer, Serializer};

    pub fn serialize<S: Serializer>(val: &Option<Vec<u8>>, s: S) -> Result<S::Ok, S::Error> {
        match val {
            Some(b) => serde_bytes::serialize(b, s),
            None => s.serialize_none(),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<Vec<u8>>, D::Error> {
        Ok(Some(serde_bytes::deserialize(d)?))
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Person {
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub age: Option<i64>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub active: Option<bool>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub score: Option<f64>,
    #[serde(default, skip_serializing_if = \"Option::is_none\", with = \"opt_bytes\")]
    pub photo: Option<Vec<u8>>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub fpn: Option<i64>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub phone: Option<PhoneNumber>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub phones: Option<Vec<PhoneNumber>>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub children: Option<Vec<Person>>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub tags: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub numbers: Option<Vec<i64>>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub flags: Option<Vec<bool>>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub values: Option<Vec<f64>>,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PhoneNumber {
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub number: Option<String>,
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub r#type: Option<i64>,
}
";
        assert_eq!(code, expected);
    }

    #[test]
    fn test_generate_both_mode() {
        let code = generate(&[SCHEMA], CodegenMode::Both).unwrap();
        let expected = "\
// Auto-generated by sproto-codegen. DO NOT EDIT.

use serde::{Serialize, Deserialize};
use sproto::{SprotoEncode, SprotoDecode};
use serde_bytes;

mod opt_bytes {
    use serde::{Deserializer, Serializer};

    pub fn serialize<S: Serializer>(val: &Option<Vec<u8>>, s: S) -> Result<S::Ok, S::Error> {
        match val {
            Some(b) => serde_bytes::serialize(b, s),
            None => s.serialize_none(),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Option<Vec<u8>>, D::Error> {
        Ok(Some(serde_bytes::deserialize(d)?))
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize, SprotoEncode, SprotoDecode)]
pub struct Person {
    #[sproto(tag = 0)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub name: Option<String>,
    #[sproto(tag = 1)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub age: Option<i64>,
    #[sproto(tag = 2)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub active: Option<bool>,
    #[sproto(tag = 3)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub score: Option<f64>,
    #[sproto(tag = 4)]
    #[serde(default, skip_serializing_if = \"Option::is_none\", with = \"opt_bytes\")]
    pub photo: Option<Vec<u8>>,
    #[sproto(tag = 5)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub fpn: Option<i64>,
    #[sproto(tag = 6)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub id: Option<i64>,
    #[sproto(tag = 7)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub phone: Option<PhoneNumber>,
    #[sproto(tag = 8)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub phones: Option<Vec<PhoneNumber>>,
    #[sproto(tag = 9)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub children: Option<Vec<Person>>,
    #[sproto(tag = 10)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub tags: Option<Vec<String>>,
    #[sproto(tag = 11)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub numbers: Option<Vec<i64>>,
    #[sproto(tag = 12)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub flags: Option<Vec<bool>>,
    #[sproto(tag = 13)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub values: Option<Vec<f64>>,
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize, SprotoEncode, SprotoDecode)]
pub struct PhoneNumber {
    #[sproto(tag = 0)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub number: Option<String>,
    #[sproto(tag = 1)]
    #[serde(default, skip_serializing_if = \"Option::is_none\")]
    pub r#type: Option<i64>,
}
";
        assert_eq!(code, expected);
    }

    #[test]
    fn test_generate_multi_files() {
        let schema_a = "\
.PhoneNumber {
    number 0 : string
    type 1 : integer
}
";
        let schema_b = "\
.Person {
    name 0 : string
    phone 1 : PhoneNumber
    phones 2 : *PhoneNumber
}
";
        let code = generate(&[schema_a, schema_b], CodegenMode::Derive).unwrap();
        let expected = "\
// Auto-generated by sproto-codegen. DO NOT EDIT.

use sproto::{SprotoEncode, SprotoDecode};

#[derive(Debug, Clone, PartialEq, Default, SprotoEncode, SprotoDecode)]
pub struct Person {
    #[sproto(tag = 0)]
    pub name: Option<String>,
    #[sproto(tag = 1)]
    pub phone: Option<PhoneNumber>,
    #[sproto(tag = 2)]
    pub phones: Option<Vec<PhoneNumber>>,
}

#[derive(Debug, Clone, PartialEq, Default, SprotoEncode, SprotoDecode)]
pub struct PhoneNumber {
    #[sproto(tag = 0)]
    pub number: Option<String>,
    #[sproto(tag = 1)]
    pub r#type: Option<i64>,
}
";
        assert_eq!(code, expected);
    }
}
